[package]
name = "dust"
version = "0.1.0"
authors = ["Asger Nyman Christiansen <asgernyman@gmail.com>"]
edition = "2018"

[dependencies]
gl = { path = "lib/gl" }
cgmath = "0.16.1"
wavefront_obj = "5.1.0"
window = { path = "lib/window" }
simplex = { path = "lib/simplex" }

[dependencies.image]
version = "0.21.0"
default-features = false
features = ["gif_codec", "jpeg", "ico", "png_codec", "pnm", "tga", "tiff", "webp", "bmp", "hdr", "dxt"]

[dev-dependencies]
rand = "0.6.5"

[features]
gl_debug = ["gl/debug"]
