[package]
name = "dust"
version = "0.1.0"
authors = ["Asger Nyman Christiansen <asgernyman@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
core = { path = "lib/core" }
wavefront_obj = "5.1.0"
window = { path = "lib/window" }
num = "0.2.0"
num-traits = "0.2"
num-derive = "0.2.4"
log = "0.4"

[dev-dependencies]
tri-mesh = "0.4.0"
wasm-bindgen = "0.2.40"
console_error_panic_hook = "0.1.5"
console_log = "0.1"

[features]
gl_debug = ["core/gl_debug"]
