[package]
name = "dust"
version = "0.1.0"
authors = ["Asger Nyman Christiansen <asgernyman@gmail.com>"]

[dependencies]
gust = { path = "lib/Gust" }
gl = { path = "lib/gl" }
num-traits = "0.2.2"

[dev-dependencies]
sdl2 = "0.31.0"

[target.'cfg(target_os = "emscripten")'.dependencies]
emscripten-sys = "0.3"

[features]
gl_debug = ["gl/debug"]
