[package]
name = "dust"
version = "0.1.0"
authors = ["Asger Nyman Christiansen <asgernyman@gmail.com>"]
edition = "2018"

[dependencies]
gl = { path = "lib/gl" }
image = "0.19.0"
cgmath = "0.16.1"
wavefront_obj = "5.1.0"
window = { path = "lib/window" }

[dev-dependencies]
noise = "0.5.1"
rand = "0.5.5"

[features]
gl_debug = ["gl/debug"]
