[package]
name = "dust"
version = "0.1.0"
authors = ["Asger Nyman Christiansen <asgernyman@gmail.com>"]

[dependencies]
gl = { path = "lib/gl" }
sdl2 = "0.31.0"
glm = "0.2.3"

[features]
gl_debug = ["gl/debug"]
