[package]
name = "dust"
version = "0.1.0"
authors = ["Asger Nyman Christiansen <asgernyman@gmail.com>"]
edition = "2018"

[dependencies]
core = { path = "lib/core" }
window = { path = "lib/window" }
wavefront_obj = "7.0"
num = "0.2"
num-traits = "0.2"
num-derive = "0.3"
log = "0.4"

[dev-dependencies]
tri-mesh = "0.4.0"

[features]
gl_debug = ["core/gl_debug"]
