[package]
name = "dust"
version = "0.1.0"
authors = ["Asger Nyman Christiansen <asgernyman@gmail.com>"]
edition = "2018"

[features]
default = ["glutin-window", "obj-loader"]
core-only = []
glutin-window = ["glutin"]
web = ["web-sys"] # Build for web target, otherwise build for desktop
canvas = ["wasm-bindgen"]
obj-loader = ["wavefront_obj"]
gl-debug = ["gl/debug"]

[dependencies]
gl = { path = "lib/gl" }
cgmath = "0.17"
num = "0.2"
num-traits = "0.2"
num-derive = "0.3"
log = "0.4"
wavefront_obj = { version = "7.0", optional = true }
glutin = { version = "0.19.0", optional = true }
wasm-bindgen = { version = "0.2.42", optional = true }

[dependencies.web-sys]
version = "0.3.19"
optional = true
features = ['Document', 'Element', 'Node', 'HtmlElement', 'HtmlCanvasElement', 'Window', 'Event', 'MouseEvent', 'EventTarget', 'WheelEvent',
  'KeyboardEvent', 'TouchEvent', 'TouchList', 'Touch']

[dependencies.image]
version = "0.22"
default-features = false
features = ["gif_codec", "jpeg", "ico", "png_codec", "pnm", "tga", "tiff", "webp", "bmp", "hdr", "dxt"]

[dev-dependencies]
tri-mesh = "0.4.0"