[package]
name = "hello_world_web"
version = "0.1.0"
authors = ["Asger Nyman Christiansen <asgernyman@gmail.com>"]
edition = "2018"

[dependencies]
dust = { path = "../../" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2.33"
