[package]
name = "hello_world_web"
version = "0.1.0"
authors = ["Asger Nyman Christiansen <asgernyman@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
dust = { path = "../../" }
window = { path = "../../lib/window" }
wasm-bindgen = "0.2.33"
